default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
  - repo: https://github.com/psf/black
    rev: 23.9.0
    hooks:
      - id: black