train:
  url: https://drive.google.com/uc?id=171j-K5YA6taPHu34MbwiQ3W2LQkCJ3Qc
  filename: creditcard_train.csv
test:
  url: https://drive.google.com/uc?id=1LyJRgk1prXworljO7bzgrupAEnZsuwlg
  filename: creditcard_test.csv
model_name: model.json
result_file: Class_pred.csv
label_column: Class
drop_column:
  - id
